// WALLETs
import 'package:walletup/common/models.dart';

final List<WalletModel> walletsTemplate = [
  WalletModel(
    1,
    1,
    1,
    "Viagem de Buenos Aires",
    "Lorem ipsum dolor la la la",
    [
      SharedContactModel(1, "cab@gmail.com"),
    ],
    [
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        -400.0,
        1,
        CategoryModel(1, 'EXPENSES'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
    ],
    DateTime.now(),
    DateTime.now(),
  ),
  WalletModel(
    1,
    1,
    1,
    "Viagem de Buenos Aires",
    "Lorem ipsum dolor la la la",
    [
      SharedContactModel(1, "cab@gmail.com"),
    ],
    [
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        -400.0,
        1,
        CategoryModel(1, 'EXPENSES'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
    ],
    DateTime.now(),
    DateTime.now(),
  ),
  WalletModel(
    1,
    1,
    1,
    "Viagem de Buenos Aires",
    "Lorem ipsum dolor la la la",
    [
      SharedContactModel(1, "cab@gmail.com"),
    ],
    [
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        -400.0,
        1,
        CategoryModel(1, 'EXPENSES'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
    ],
    DateTime.now(),
    DateTime.now(),
  ),
  WalletModel(
    1,
    1,
    1,
    "Viagem de Buenos Aires",
    "Lorem ipsum dolor la la la",
    [
      SharedContactModel(1, "cab@gmail.com"),
    ],
    [
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        -400.0,
        1,
        CategoryModel(1, 'EXPENSES'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
      TransactionModel(
        1,
        1,
        150.0,
        1,
        CategoryModel(1, 'PROFIT'),
        WalletBasicModel(
          1,
          "Viagem de Buenos Aires",
          "Lorem ipsum dolor la la la",
        ),
        'Ola mundo',
        DateTime.now(),
      ),
    ],
    DateTime.now(),
    DateTime.now(),
  )
];
